# Generated by Django 3.1.3 on 2020-11-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_created=True)),
                ('prdName', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('StorageCode', models.IntegerField(primary_key=True, serialize=False)),
                ('StorageLoc', models.CharField(max_length=20)),
                ('StorageStock', models.IntegerField()),
                ('StorageUse', models.BooleanField(default=False)),
                ('StroageTel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('SupplyerCode', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplyerName', models.CharField(max_length=20)),
                ('SupplyerAddr', models.CharField(max_length=50)),
                ('SupplyerTel', models.CharField(max_length=20)),
                ('SupplyerEmail', models.EmailField(max_length=20, unique=True)),
                ('SupplyerBankName', models.CharField(max_length=20)),
                ('SupplyerAccount', models.CharField(max_length=20)),
                ('AccountHolder', models.CharField(max_length=20)),
            ],
        ),
    ]
